

# Generated by Django 6.0.6 on 2026-06-12 12:00

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
