version: '5.3'
services:
  postgres_db:
    image: pgvector/pgvector:pg17
    container_name: postgres_pgvector
    restart: always
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

    volumes:
      - postgres_data_v:/var/lib/postgresql/data

  redis_db:
    image: redis:7.2-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build: ./frontend
    container_name: e_kyc_frontend
    restart: always
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      BACKEND_ORIGIN: http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"


  web_backend:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_backend
    volumes:
      - media_data:/app/media
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    
  celery_worker:
    build: ./backend
    restart: always
    command: celery -A config worker --loglevel=info
    container_name: celery_worker
    volumes:
      - media_data:/app/media
    depends_on:
      - postgres_db
      - redis_db
   

volumes:
  postgres_data_v:
  redis_data:
  media_data:
