version: '3.8'
services:
  postgres_db:
    image: pgvector/pgvector:pg17
    container_name: postgres_pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v:/var/lib/postgresql/data

  redis_db:
    image: redis:7.2-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

 

  web_backend:
    image: ${DOCKERHUB_USERNAME}/ekyc-web-backend:${IMAGE_TAG}
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_backend
    volumes:
      - media_data:/app/media
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
    depends_on:
      redis_db:
        condition: service_healthy
    ports:
      - "8000:8000"

  celery_worker:
    image: ${DOCKERHUB_USERNAME}/ekyc-web-backend:${IMAGE_TAG}
    restart: always
    command: celery -A config worker --loglevel=info
    container_name: celery_worker
    volumes:
      - media_data:/app/media
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
    depends_on:
      redis_db:
        condition: service_healthy

volumes:
  redis_data:
  media_data:
  postgres_data_v: